import {
  Sliders,
  User,
  Heart,
  Sparkles,
  Watch,
  Lock,
  Bell,
  CreditCard,
  ShieldCheck,
} from 'lucide-react';
import { SettingsTabMeta, SearchableSettingItem } from './types';

export const SETTINGS_TABS: SettingsTabMeta[] = [
  {
    id: 'general',
    label: 'General System',
    shortLabel: 'General',
    icon: Sliders,
    description: 'System language, timezone, units format and local caching preferences.',
    keywords: ['language', 'timezone', 'units', 'metric', 'imperial', 'date format', 'auto save', 'cloud backup', 'offline mode'],
  },
  {
    id: 'account',
    label: 'Account Specs',
    shortLabel: 'Account',
    icon: User,
    description: 'Personal athlete specs, verified identity, contact info and profile status.',
    keywords: ['profile', 'name', 'username', 'email', 'phone', 'emergency contact', 'avatar'],
  },
  {
    id: 'health',
    label: 'Health Goals',
    shortLabel: 'Health',
    icon: Heart,
    description: 'Daily biomarkers, target weight, hydration threshold and circadian recovery metrics.',
    keywords: ['weight', 'calories', 'water', 'sleep', 'workout days', 'heart rate', 'hydration', 'biomarkers', 'recovery'],
  },
  {
    id: 'aicoach',
    label: 'AI Coach Engine',
    shortLabel: 'AI Engine',
    icon: Sparkles,
    badge: 'v3.4',
    description: 'Neural coach personality, analysis depth, creativity temperature and predictive models.',
    keywords: ['ai', 'coach', 'personality', 'athlete', 'strict', 'doctor', 'friendly', 'voice', 'creativity', 'neural'],
  },
  {
    id: 'devices',
    label: 'Connected Devices',
    shortLabel: 'Devices',
    icon: Watch,
    badge: '5 Active',
    description: 'Wearable telemetry matrix, battery diagnostics and real-time biometric sensors.',
    keywords: ['apple watch', 'whoop', 'oura ring', 'garmin', 'withings', 'smartwatch', 'bluetooth', 'sync', 'battery'],
  },
  {
    id: 'security',
    label: 'Security & 2FA',
    shortLabel: 'Security',
    icon: Lock,
    description: 'Multi-factor authentication, biometric Face ID access, active sessions and credential vault.',
    keywords: ['password', '2fa', 'two-factor', 'biometric', 'face unlock', 'fingerprint', 'sessions', 'security score'],
  },
  {
    id: 'notifications',
    label: 'Notifications & Alerts',
    shortLabel: 'Alerts',
    icon: Bell,
    description: 'Circadian workout reminders, nutrient alert triggers and cross-channel delivery.',
    keywords: ['notifications', 'push', 'email', 'sms', 'reminders', 'workout alert', 'hydration alert', 'sleep reminder'],
  },
  {
    id: 'billing',
    label: 'Billing & Plan',
    shortLabel: 'Billing',
    icon: CreditCard,
    badge: 'Pro Tier',
    description: 'Subscription management, active membership tier, payment methods and invoices.',
    keywords: ['billing', 'subscription', 'plan', 'pro', 'invoices', 'payment method', 'credit card', 'receipts'],
  },
  {
    id: 'privacy',
    label: 'Privacy & Data',
    shortLabel: 'Privacy',
    icon: ShieldCheck,
    description: 'HIPAA & GDPR encryption envelope, telemetry sharing and exportable athlete archive.',
    keywords: ['privacy', 'hipaa', 'gdpr', 'encryption', 'data export', 'download archive', 'delete account', 'danger zone'],
  },
];

export const SEARCHABLE_SETTINGS: SearchableSettingItem[] = [
  {
    id: 'general-language',
    tabId: 'general',
    tabLabel: 'General System',
    title: 'System Language',
    description: 'Change application language (English, Spanish, Hindi, Marathi).',
    keywords: ['language', 'locale', 'english', 'spanish', 'hindi', 'marathi'],
  },
  {
    id: 'general-timezone',
    tabId: 'general',
    tabLabel: 'General System',
    title: 'Timezone Synchronization',
    description: 'Align timestamp calculations to Pacific, Eastern, or IST.',
    keywords: ['timezone', 'utc', 'clock', 'time', 'sync'],
  },
  {
    id: 'general-units',
    tabId: 'general',
    tabLabel: 'General System',
    title: 'Measurement Units',
    description: 'Toggle between Metric (kg, cm, km) and Imperial (lbs, in, miles).',
    keywords: ['units', 'metric', 'imperial', 'kg', 'lbs', 'miles', 'km'],
  },
  {
    id: 'general-backup',
    tabId: 'general',
    tabLabel: 'General System',
    title: 'Encrypted Cloud Backup & Auto-Save',
    description: 'Manage automated background saving and encrypted cloud sync.',
    keywords: ['backup', 'auto save', 'cloud', 'sync', 'offline'],
  },
  {
    id: 'account-names',
    tabId: 'account',
    tabLabel: 'Account Specs',
    title: 'Profile Information',
    description: 'Update athlete legal first name, last name, and display handle.',
    keywords: ['name', 'first name', 'last name', 'profile', 'specs', 'display'],
  },
  {
    id: 'account-contact',
    tabId: 'account',
    tabLabel: 'Account Specs',
    title: 'Phone & Emergency Contact',
    description: 'Emergency dispatcher contact and SMS telemetry phone number.',
    keywords: ['phone', 'contact', 'emergency', 'sms', 'telephone'],
  },
  {
    id: 'health-weight',
    tabId: 'health',
    tabLabel: 'Health Goals',
    title: 'Target Weight & Calorie Intake',
    description: 'Configure daily caloric target and target scale weight.',
    keywords: ['weight', 'calories', 'target weight', 'diet', 'kcal'],
  },
  {
    id: 'health-water-sleep',
    tabId: 'health',
    tabLabel: 'Health Goals',
    title: 'Hydration & Sleep Objectives',
    description: 'Set daily water intake (liters) and circadian sleep goal (hours).',
    keywords: ['water', 'hydration', 'sleep', 'rest', 'hours', 'liters'],
  },
  {
    id: 'health-hr-alert',
    tabId: 'health',
    tabLabel: 'Health Goals',
    title: 'Peak Heart Rate Threshold Alert',
    description: 'Set safe cardiovascular upper boundary alert in BPM.',
    keywords: ['heart rate', 'bpm', 'pulse', 'cardio', 'alert', 'threshold'],
  },
  {
    id: 'ai-persona',
    tabId: 'aicoach',
    tabLabel: 'AI Coach Engine',
    title: 'AI Coach Persona & Tone',
    description: 'Select between Elite Athletic, Friendly Motivator, Strict, or Doctor.',
    keywords: ['ai', 'coach', 'persona', 'personality', 'tone', 'athletic', 'strict'],
  },
  {
    id: 'ai-creativity',
    tabId: 'aicoach',
    tabLabel: 'AI Coach Engine',
    title: 'Neural Creativity Temperature',
    description: 'Tune deterministic vs. creative recommendation models.',
    keywords: ['creativity', 'temperature', 'neural', 'variance', 'model'],
  },
  {
    id: 'ai-features',
    tabId: 'aicoach',
    tabLabel: 'AI Coach Engine',
    title: 'AI Meal & Workout Generation',
    description: 'Toggle autonomous meal planning and adaptive recovery predictions.',
    keywords: ['meal planning', 'workout suggestions', 'predictive alerts', 'voice'],
  },
  {
    id: 'devices-wearables',
    tabId: 'devices',
    tabLabel: 'Connected Devices',
    title: 'Connected Wearable Matrix',
    description: 'Pair or disconnect Apple Watch, WHOOP, Oura Ring, Garmin, and scales.',
    keywords: ['apple watch', 'whoop', 'oura', 'garmin', 'withings', 'wearable', 'bluetooth'],
  },
  {
    id: 'security-2fa',
    tabId: 'security',
    tabLabel: 'Security & 2FA',
    title: 'Two-Factor Authentication (2FA)',
    description: 'Hardware key and authenticator TOTP application protection.',
    keywords: ['2fa', 'two-factor', 'totp', 'authenticator', 'security', 'mfa'],
  },
  {
    id: 'security-biometric',
    tabId: 'security',
    tabLabel: 'Security & 2FA',
    title: 'Biometric & Face ID Unlock',
    description: 'Authenticate securely using device fingerprint or facial geometry.',
    keywords: ['biometric', 'face id', 'touch id', 'fingerprint', 'unlock'],
  },
  {
    id: 'security-password',
    tabId: 'security',
    tabLabel: 'Security & 2FA',
    title: 'Password & Active Sessions',
    description: 'Review authorized login devices and change account password.',
    keywords: ['password', 'change password', 'sessions', 'devices', 'login'],
  },
  {
    id: 'notif-circadian',
    tabId: 'notifications',
    tabLabel: 'Notifications & Alerts',
    title: 'Circadian Workout & Meal Alerts',
    description: 'Smart timing alerts based on biological clocks and rest intervals.',
    keywords: ['workout alert', 'meal reminder', 'circadian', 'notifications'],
  },
  {
    id: 'notif-channels',
    tabId: 'notifications',
    tabLabel: 'Notifications & Alerts',
    title: 'Delivery Channels (Push, Email, SMS)',
    description: 'Choose which communication channels receive critical updates.',
    keywords: ['push', 'email', 'sms', 'text message', 'channels'],
  },
  {
    id: 'billing-tier',
    tabId: 'billing',
    tabLabel: 'Billing & Plan',
    title: 'Pro AI Membership Subscription',
    description: 'Review active subscription features, billing interval, and renewal date.',
    keywords: ['subscription', 'pro', 'plan', 'membership', 'tier', 'cost', 'renew'],
  },
  {
    id: 'billing-invoices',
    tabId: 'billing',
    tabLabel: 'Billing & Plan',
    title: 'Payment Method & Invoice History',
    description: 'Update payment card and download official tax receipts.',
    keywords: ['invoices', 'receipts', 'credit card', 'visa', 'payment', 'download'],
  },
  {
    id: 'privacy-hipaa',
    tabId: 'privacy',
    tabLabel: 'Privacy & Data',
    title: 'HIPAA & GDPR Encryption Envelope',
    description: 'End-to-end AES-256 telemetry security certificates and guarantees.',
    keywords: ['hipaa', 'gdpr', 'encryption', 'aes-256', 'compliance', 'security'],
  },
  {
    id: 'privacy-export',
    tabId: 'privacy',
    tabLabel: 'Privacy & Data',
    title: 'Export Athlete Data Archive',
    description: 'Download full JSON & CSV archive of all workouts, meals, and vitals.',
    keywords: ['export', 'download', 'archive', 'csv', 'json', 'data', 'backup'],
  },
  {
    id: 'privacy-delete',
    tabId: 'privacy',
    tabLabel: 'Privacy & Data',
    title: 'Danger Zone: Delete Account',
    description: 'Permanently purge all biometric telemetry and delete cloud account.',
    keywords: ['delete', 'danger', 'purge', 'close account', 'remove data'],
  },
];
